services:
  app:
    image: python:3.10.12
    container_name: tg_bot
    command: sh -c "pip install -r requirements.txt && python -u bot_v2_with_threads.py"
    working_dir: /app
    volumes:
      - ./:/app