version: '3.8'

services:
  tg_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_bot
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped